spring.application.name=macrohedge-backend

# Server Port
server.port=8081

# ===================================================================
# MS SQL SERVER VERİTABANI BAĞLANTISI (SQL Express)
# ===================================================================
# Windows Authentication veya 'sa' kullanıcına göre URL'i ayarlıyoruz
spring.datasource.url=jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=MacroHedge Core;encrypt=false;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Veritabanı Kullanıcı Adı ve Şifren (SSMS'e girerken kullandığın bilgiler)
# Eğer Windows Authentication kullanıyorsan sa kullanıcısını aktif edip şifre belirleyebilir
# ya da buraya SQL Server kullanıcını yazabilirsin:
spring.datasource.username=sa
spring.datasource.password=123456

# ===================================================================
# JPA / HIBERNATE AYARLARI (Senior Mimar Notu!)
# ===================================================================
# Tabloları elle SQL scripti ile kurduğumuz için Hibernate'e 'validate' diyoruz.
# Hibernate tabloları baştan yaratmasın veya bozmasın, sadece Java sınıfları ile SQL tabloları eşleşiyor mu doğrulassın!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===================================================================
# PYTHON MİKROSERVİS ADRESİ (Market Data & AI Service)
# ===================================================================
python.market-service.url=http://localhost:8000